from . import account_edi_format
from . import account_move
from . import colony
from . import fleet_vehicle_configuration
from . import fleet_vehicle_trailer_subtype
from . import fleet_vehicle
from . import hazardous_material
from . import packaging
from . import postal_code
from . import res_partner
from . import sat_merchandise_code
from . import tms_waybill_transportable_line
from . import tms_waybill
