from . import fleet_vehicle_engine
from . import fleet_vehicle_log_fuel_prepaid
from . import fleet_vehicle_odometer
from . import fleet_vehicle_log_fuel
from . import fleet_vehicle
from . import hr_employee
from . import operating_unit
from . import product_template
from . import res_company
from . import res_config_settings
from . import tms_advance
from . import tms_custom_house
from . import tms_customs
from . import tms_event
from . import tms_expense_line
from . import tms_expense_loan
from . import tms_expense
from . import tms_extradata_type
from . import tms_extradata
from . import tms_factor
from . import tms_place
from . import tms_retention
from . import tms_route_fuelefficiency
from . import tms_route_note
from . import tms_route_place
from . import tms_route_tollstation_costperaxis
from . import tms_route_tollstation
from . import tms_route
from . import tms_toll_data
from . import tms_toll_import
from . import tms_transportable
from . import tms_travel
from . import tms_unit_kit
from . import tms_waybill_line
from . import tms_waybill_taxes
from . import tms_waybill_transportable_line
from . import tms_waybill
from . import account_bank_statement_line
from . import account_move
from . import res_partner
