# -*- coding: utf-8 -*-
{
    'name': 'Freight Management',
    'version': '16.0.0.0.3',
    'category': 'Transport',
    'summary': 'Management System for Carriers, Trucking and other companies',
    'author': 'Quadro Soluciones',
    'website': 'https://quadrosoluciones.com/',
    "license": "LGPL-3",
    'depends': [
        'account_accountant',
        'fleet',
        'hr',
        'account_operating_unit',
        'operating_unit',
        'base'
    ],
    'data': [
        'data/paper_formats.xml',
        'data/ir_sequence_data.xml',
        'data/account_journal_data.xml',
        'data/product_product_data.xml',
        'data/ir_config_parameter.xml',
        'data/operating_unit_data.xml',
        'security/tms_groups.xml',
        'security/ir.model.access.csv',
        'security/tms_rules.xml',
        'reports/report_layouts.xml',
        'reports/tms_expense_report.xml',
        'reports/tms_waybill_report.xml',
        'reports/tms_travel_instructions_letter.xml',
        'reports/tms_op_expense_report.xml',
        'reports/tms_highway_report.xml',
        'views/account_move_views.xml',
        'views/fleet_vehicle_views.xml',
        'views/fleet_vehicle_engine_views.xml',
        'views/tms_unit_kit_views.xml',
        'views/fleet_vehicle_odometer_views.xml',
        'views/tms_custom_house_views.xml',
        'views/tms_customs_views.xml',
        'views/tms_transportable_views.xml',
        'views/tms_place_views.xml',
        'views/tms_route_tollstation_views.xml',
        'views/hr_employee_views.xml',
        'views/res_config_settings_views.xml',
        'views/tms_retention_views.xml',
        'views/tms_expense_loan_views.xml',
        'views/tms_route_views.xml',
        'views/operating_unit_views.xml',
        'views/tms_extradata_views.xml',
        'views/fleet_vehicle_log_fuel_views.xml',
        'views/product_template_views.xml',
        'views/tms_travel_views.xml',
        'views/tms_advance_views.xml',
        'views/fleet_vehicle_log_fuel_prepaid_views.xml',
        'views/tms_waybill_views.xml',
        'views/tms_expense_views.xml',
        'views/tms_expense_line_views.xml',
        'views/tms_toll_data_views.xml',
        'views/tms_route_note_views.xml',
        #'views/res_partner_views.xml',
        'views/tms_factor_views.xml',
        'views/tms_event_views.xml',
        'views/tms_waybill_line_views.xml',
        'views/tms_waybill_transportable_line_views.xml',
        'wizards/tms_toll_import_wizard_views.xml',
        'wizards/tms_payment_wizard_views.xml',
        'wizards/tms_invoice_wizard_views.xml',
        'views/views_menu_items.xml'
    ],
    'application': True,
    'installable': True
}
