{
    'name': 'Endpoint Catalog',
    'version': '16.0.0.3',
    'category': 'Extra Tools',
    'description': 'Manages a catalog of REST endpoints. Define URL, Method, Body, Response, Headers and hardcode Authorization (or not). Call from python functions or modules on demand. ',
    'author': 'Quadro Soluciones',
    'images': [],
    'depends': ['base', 'contacts'],
    'installable': True,
    'application': True,
    'data': [
        'security/ir.model.access.csv',
        'views/body_views.xml',
        'views/response_views.xml',
        'views/header_views.xml',
        'views/endpoint_views.xml',
        'views/actions.xml',
        'views/menus.xml',
    ],
}
